        <script src="<%=application.getContextPath()%>/js/jquery.min.js"></script>
        <script src="<%=application.getContextPath()%>/js/modernizr.custom.js"></script>
        <script src="<%=application.getContextPath()%>/js/jquery.easing.1.3.js"></script>
        <script src="<%=application.getContextPath()%>/js/bootstrap.min.js"></script>
        <script src="<%=application.getContextPath()%>/plugins/flexslider/jquery.flexslider-min.js"></script> 
        <script src="<%=application.getContextPath()%>/plugins/flexslider/flexslider.config.js"></script>
        <script src="<%=application.getContextPath()%>/js/jquery.appear.js"></script>
        <script src="<%=application.getContextPath()%>/js/stellar.js"></script>
        <script src="<%=application.getContextPath()%>/js/classie.js"></script>
        <script src="<%=application.getContextPath()%>/js/uisearch.js"></script>
        <script src="<%=application.getContextPath()%>/js/jquery.cubeportfolio.min.js"></script>
        <script src="<%=application.getContextPath()%>/js/google-code-prettify/prettify.js"></script>
        <script src="<%=application.getContextPath()%>/js/animate.js"></script>
        <script src="<%=application.getContextPath()%>/js/custom.js"></script>